---
title: "HiddenPoales"
author: "Marcial Escudero"
date: '2022-10-07'
output: html_document
editor_options: 
  chunk_output_type: console
---



More complex models with openclosed, annualperennial and photosynthesis

```{r}
#install.packages("corHMM")

library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
mytree <- read.tree(file="final_tree.tree")
mytree

trait1 <- cbind(traits$WCVP_name, traits$open_closed)
trait4 <- cbind(traits$WCVP_name, traits$annual_perennial)
trait11 <- cbind(traits$WCVP_name, traits$C4)
trait5 <- cbind(traits$WCVP_name, traits$CAM)
trait11[,2][trait11[,2] == ""] <- NA
trait11[,2][trait5[,2] == 1] <- 2
trait11[,2][trait11[,2] == "1"] <- 1
trait11[,2][trait11[,2] == "0"] <- 0
trait11[,2][trait11[,2] == "01"] <- 1
trait1[,2][trait1[,2] == ""] <- NA
trait1[,2][trait1[,2] == "1"] <- 1
trait1[,2][trait1[,2] == "0"] <- 0
trait1[,2][trait1[,2] == "01"] <- 1
trait4[,2][trait4[,2] == ""] <- NA
trait4[,2][trait4[,2] == "1"] <- 1
trait4[,2][trait4[,2] == "0"] <- 0
trait4[,2][trait4[,2] == "01"] <- 1
trait12 <- cbind(trait1, trait4,trait11)
trait12 <- trait12[,c(1,2,4,6)]
trait12<-trait12[!is.na(trait12[,2]),]
trait12<-trait12[!is.na(trait12[,3]),]
trait12<-trait12[!is.na(trait12[,4]),]

tipstoremove <- setdiff(mytree$tip.label,trait12[,1])

mytree <- drop.tip(mytree, tipstoremove)

setdiff(trait12[,1], mytree$tip.label)
setdiff(mytree$tip.label,trait12[,1])

pp.polymorphic12a<-corHMM(mytree,trait12[,c(1,2,3)],rate.cat=2,node.states="marginal")
pp.polymorphic12a
pp.polymorphic12a.1<-corHMM(mytree,trait12[,c(1,2,3)],rate.cat=1,node.states="marginal")
pp.polymorphic12a.1
pp.polymorphic12a.2<-corHMM(mytree,trait12[,c(1,2,3)],rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic12a.2
pp.polymorphic12a.3<-corHMM(mytree,trait12[,c(1,2,3)],rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic12a.3

LegendAndRateMat <- getStateMat4Dat(trait12[,c(1,2,4)])
LegendAndRateMat
RateMat <- LegendAndRateMat$rate.mat
RateMat
RateMat[2,3] <- 0
RateMat[3,2] <- 0
RateMat[5,6] <- 0
RateMat[6,5] <- 0
RateMat[5,2] <- 5
RateMat[1,3] <- 6
RateMat[6,3] <- 7
RateMat[1,4] <- 8
RateMat[5,4] <- 9
RateMat[6,4] <- 10
RateMat[2,5] <- 11
RateMat[4,5] <- 12
RateMat[2,5] <- 11
RateMat[4,5] <- 12
RateMat[3,6] <- 13
RateMat[4,6] <- 14
RateMat
RateClassMat <- getRateCatMat(2) #
RateClassMat <- equateStateMatPars(RateClassMat, c(1,2))
RateClassMat
StateMats <- list(RateMat, RateMat)
StateMats
FullMat <- getFullMat(StateMats, RateClassMat)
FullMat
RateMatsym <- RateMat
RateMatsym
RateMatsym[5,4] <- 1
RateMatsym[6,4] <- 2
RateMatsym[4,5] <- 4
RateMatsym[4,6] <- 6
RateMatsym[1,4] <- 3
RateMatsym[2,5] <- 5
RateMatsym[3,6] <- 7
RateMatsym
StateMatssym <- list(RateMatsym, RateMatsym)
StateMatssym
FullMatsym <- getFullMat(StateMatssym, RateClassMat)
FullMatsym
pp.polymorphic12b<-corHMM(mytree,trait12[,c(1,2,4)],rate.cat=2,rate.mat = FullMat, node.states="marginal")
pp.polymorphic12b
pp.polymorphic12b.1<-corHMM(mytree,trait12[,c(1,2,4)],rate.cat=1,rate.mat = RateMat, node.states="marginal")
pp.polymorphic12b.1
pp.polymorphic12b.2<-corHMM(mytree,trait12[,c(1,2,4)],rate.cat=2, rate.mat = FullMatsym, node.states="marginal")
pp.polymorphic12b.2
pp.polymorphic12b.3<-corHMM(mytree,trait12[,c(1,2,4)],rate.cat=1,rate.mat = RateMatsym, node.states="marginal")
pp.polymorphic12b.3

pp.polymorphic12c<-corHMM(mytree,trait12[,c(1,2)],rate.cat=2,node.states="marginal")
pp.polymorphic12c
pp.polymorphic12c.1<-corHMM(mytree,trait12[,c(1,2)],rate.cat=1,node.states="marginal")
pp.polymorphic12c.1
pp.polymorphic12c.2<-corHMM(mytree,trait12[,c(1,2)],rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic12c.2
pp.polymorphic12c.3<-corHMM(mytree,trait12[,c(1,2)],rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic12c.3

pp.polymorphic12d<-corHMM(mytree,trait12[,c(1,3)],rate.cat=2,node.states="marginal")
pp.polymorphic12d
pp.polymorphic12d.1<-corHMM(mytree,trait12[,c(1,3)],rate.cat=1,node.states="marginal")
pp.polymorphic12d.1
pp.polymorphic12d.2<-corHMM(mytree,trait12[,c(1,3)],rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic12d.2
pp.polymorphic12d.3<-corHMM(mytree,trait12[,c(1,3)],rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic12d.3

LegendAndRateMat <- getStateMat4Dat(trait12[,c(1,4)])
RateMat <- LegendAndRateMat$rate.mat
RateMat
RateMat[2,3] <- 0
RateMat[3,2] <- 0
RateMat[1,3] <- 4
RateMat
RateClassMat <- getRateCatMat(2) #
RateClassMat <- equateStateMatPars(RateClassMat, c(1,2))
RateClassMat
StateMats <- list(RateMat, RateMat)
StateMats
FullMat <- getFullMat(StateMats, RateClassMat)
FullMat
RateMatsym <- RateMat
RateMatsym[1,2] <- 1
RateMatsym[1,3] <- 2
RateMatsym
StateMatssym <- list(RateMatsym, RateMatsym)
StateMatssym
FullMatsym <- getFullMat(StateMatssym, RateClassMat)
FullMatsym
pp.polymorphic12e<-corHMM(mytree,trait12[,c(1,4)],rate.cat=2, rate.mat = FullMat, node.states="marginal")
pp.polymorphic12e
pp.polymorphic12e.1<-corHMM(mytree,trait12[,c(1,4)],rate.cat=1,rate.mat = RateMat, node.states="marginal")
pp.polymorphic12e.1
pp.polymorphic12e.2<-corHMM(mytree,trait12[,c(1,4)],rate.cat=2, rate.mat = FullMatsym, node.states="marginal")
pp.polymorphic12e.2
pp.polymorphic12e.3<-corHMM(mytree,trait12[,c(1,4)],rate.cat=1, rate.mat = RateMatsym, node.states="marginal")
pp.polymorphic12e.3

#open_close_C3C4CAM
pdffn = paste0("corHMMmodel_open_close_C3C4CAM.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12b, rate.cat = 2, color = "col.blind" )
dev.off()
#"0_0" "0_1" "0_2" "1_0" "1_1" "1_2" 
cols <- c("white", "black", "blue", "purple", "cyan", "grey", "red", "yellow", "orange", "green", "pink", "darkgreen")
pdffn = paste0("polymorphicARDandR1R2rates_open_close_C3C4CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12b$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Open Close C3C4CAM ARD and R1/R2 rates")
dev.off()

trait <- paste(trait12[,2],trait12[,4], sep = "_") 
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_open_close_C3C4CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "blue", "purple", "cyan", "grey", "red", "yellow", "orange", "green", "pink", "darkgreen")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAM.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAM.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
dev.off()

#"0_0" "0_1" "0_2" "1_0" "1_1" "1_2" 
#open_close_C3C4CAM
#(1,R1)       (2,R1)       (3,R1)      (4,R1)       (5,R1)       (6,R1)    (1,R2) (2,R2)       (3,R2)       (4,R2)       (5,R2)       (6,R2)
cols <- c("orange", "orange", "orange", "orange", "orange", "orange", "grey", "grey", "grey", "grey", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAMrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAMphoto.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
dev.off()

#"0_0" "0_1" "0_2" "1_0" "1_1" "1_2" 
#open_close_C3C4CAM
#(1,R1)       (2,R1)       (3,R1)      (4,R1)       (5,R1)       (6,R1)    (1,R2) (2,R2)       (3,R2)       (4,R2)       (5,R2)       (6,R2)
cols <- c("green", "blue", "red", "green", "blue", "red", "green", "blue", "red",  "green", "blue", "red")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAMphoto.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAMphoto.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
dev.off()

#"0_0" "0_1" "0_2" "1_0" "1_1" "1_2" 
#open_close_C3C4CAM
#(1,R1)       (2,R1)       (3,R1)      (4,R1)       (5,R1)       (6,R1)    (1,R2) (2,R2)       (3,R2)       (4,R2)       (5,R2)       (6,R2)
cols <- c("pink", "pink", "pink", "brown", "brown", "brown", "pink", "pink", "pink", "brown", "brown", "brown")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAMhabitats.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_C3C4CAMhabitat.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12b$states,piecol=cols,cex=0.1)
dev.off()

#open_close_annual_perennial
pdffn = paste0("corHMMmodel_open_close_annual_perennial.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12a, rate.cat = 2, color = "col.blind" )
dev.off()
#"0_0" "0_1" "1_0" "1_1" 
cols <- c("white", "black", "blue", "purple", "red", "yellow", "orange", "green")
pdffn = paste0("polymorphicARDandR1R2rates_open_close_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12a$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Open Close Annual Perennial ARD and R1/R2 rates")
dev.off()

trait <- paste(trait12[,2],trait12[,3], sep = "_") 
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_open_close_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "blue", "purple", "red", "yellow", "orange", "green")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennial.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennial.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
dev.off()

#1     2     3     4 
#"0_0" "0_1" "1_0" "1_1" 
#(1,R1)      (2,R1)      (3,R1)       (4,R1)      (1,R2)      (2,R2)      (3,R2)  (4,R2)

cols <- c("orange", "orange", "orange", "orange", "grey", "grey", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennialrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennialrates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("pink", "pink", "brown", "brown", "pink", "pink", "brown", "brown")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennialhabitat.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennialhabitat.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
dev.off()


cols <- c("green", "blue", "green", "blue", "green", "blue","green", "blue")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennialhabit.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_annual_perennialhabit.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12a$states,piecol=cols,cex=0.1)
dev.off()

#open_close

pdffn = paste0("corHMMmodel_open_closed.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12c, rate.cat = 2, color = "col.blind")
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2rates_open_closed.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12c$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Open Close ARD and R1/R2 rates")
dev.off()

trait <- trait12[,2]
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_open_closed.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closed.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closed.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
dev.off()


# 1   2 
#"0" "1" 
# (1,R1)      (2,R1)     (1,R2)      (2,R2)
cols <- c("orange", "orange", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closerates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closerates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("pink", "brown", "pink", "brown")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closehabitat.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closehabitat.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
dev.off()

#annual_perennial
pdffn = paste0("corHMMmodel_annual_perennial.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12d, rate.cat = 2, color = "col.blind")
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2rates_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12d$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Annual Perennial ARD and R1/R2 rates")
dev.off()

trait <- trait12[,3]
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennial.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennial.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
dev.off()


cols <- c("orange", "orange", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialrates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("green", "blue", "green", "blue")
pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialhabit.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialhabit.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
dev.off()

#photosynthesis

pdffn = paste0("corHMMmodel_C3C4CAM.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12e, rate.cat = 2, color = "col.blind" )
dev.off()

cols <- c("white", "black", "blue", "red", "yellow", "orange")
pdffn = paste0("polymorphicARDandR1R2rates_C3C4CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12e$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="C3C4CAM ARD and R1/R2 rates")
dev.off()

trait <- trait12[,4]
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_C3C4CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "blue", "red", "yellow", "orange")
pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAM.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAM.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
dev.off()

# 1   2   3 
#"0" "1" "2" 
# (1,R1)      (2,R1)       (3,R1)      (1,R2)      (2,R2)      (3,R2)

cols <- c("orange", "orange", "orange", "grey", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMrates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("green", "blue", "red", "green", "blue", "red")
pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMphoto.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMphoto.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
dev.off()
```



More complex models with openclosed,  pollination (wind/animal), wetness (wet/dry), growth (epiphyte/not) and silica (+/-)

```{r}
#install.packages("corHMM")

library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
mytree <- read.tree(file="final_tree.tree")
mytree

trait1 <- cbind(traits$WCVP_name, traits$open_closed)
trait5 <- cbind(traits$WCVP_name, traits$wind_animal)
trait6 <- cbind(traits$WCVP_name, traits$silica)
trait7 <- cbind(traits$WCVP_name, traits$wet)
trait9 <- cbind(traits$WCVP_name, traits$epiphyte)

trait1[,2][trait1[,2] == ""] <- NA
trait1[,2][trait1[,2] == "1"] <- 1
trait1[,2][trait1[,2] == "0"] <- 0
trait1[,2][trait1[,2] == "01"] <- 1
trait5[,2][trait5[,2] == ""] <- NA
trait5[,2][trait5[,2] == "1"] <- 1
trait5[,2][trait5[,2] == "0"] <- 0
trait5[,2][trait5[,2] == "01"] <- 1
trait6[,2][trait6[,2] == ""] <- NA
trait6[,2][trait6[,2] == "1"] <- 1
trait6[,2][trait6[,2] == "0"] <- 0
trait6[,2][trait6[,2] == "01"] <- 1
trait7[,2][trait7[,2] == ""] <- NA
trait7[,2][trait7[,2] == "1"] <- 1
trait7[,2][trait7[,2] == "0"] <- 0
trait7[,2][trait7[,2] == "01"] <- 1
trait9[,2][trait9[,2] == ""] <- NA
trait9[,2][trait9[,2] == "1"] <- 1
trait9[,2][trait9[,2] == "0"] <- 0
trait9[,2][trait9[,2] == "01"] <- 1

trait13 <- cbind(trait1, trait5,trait6,trait7,trait9)
trait13 <- trait13[,c(1,2,4,6,8,10)]
trait13<-trait13[!is.na(trait13[,2]),]
trait13<-trait13[!is.na(trait13[,3]),]
trait13<-trait13[!is.na(trait13[,4]),]
trait13<-trait13[!is.na(trait13[,5]),]
trait13<-trait13[!is.na(trait13[,6]),]

tipstoremove <- setdiff(mytree$tip.label,trait13[,1])

mytree <- drop.tip(mytree, tipstoremove)

setdiff(trait13[,1], mytree$tip.label)
setdiff(mytree$tip.label,trait13[,1])

pp.polymorphic13a<-corHMM(mytree,trait13[,c(1,2,3)],rate.cat=2,node.states="marginal")
pp.polymorphic13a
pp.polymorphic13a.1<-corHMM(mytree,trait13[,c(1,2,3)],rate.cat=1,node.states="marginal")
pp.polymorphic13a.1
pp.polymorphic13a.2<-corHMM(mytree,trait13[,c(1,2,3)],rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic13a.2
pp.polymorphic13a.3<-corHMM(mytree,trait13[,c(1,2,3)],rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic13a.3

pp.polymorphic13b<-corHMM(mytree,trait13[,c(1,2,4)],rate.cat=2,node.states="marginal")
pp.polymorphic13b
pp.polymorphic13b.1<-corHMM(mytree,trait13[,c(1,2,4)],rate.cat=1,node.states="marginal")
pp.polymorphic13b.1
pp.polymorphic13b.2<-corHMM(mytree,trait13[,c(1,2,4)],rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic13b.2
pp.polymorphic13b.3<-corHMM(mytree,trait13[,c(1,2,4)],rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic13b.3

#hasta aquí
pp.polymorphic13c<-corHMM(mytree,trait13[,c(1,2,5)],rate.cat=2,node.states="marginal")
pp.polymorphic13c
pp.polymorphic13c.1<-corHMM(mytree,trait13[,c(1,2,5)],rate.cat=1,node.states="marginal")
pp.polymorphic13c.1
pp.polymorphic13c.2<-corHMM(mytree,trait13[,c(1,2,5)],rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic13c.2
pp.polymorphic13c.3<-corHMM(mytree,trait13[,c(1,2,5)],rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic13c.3

pp.polymorphic13d<-corHMM(mytree,trait13[,c(1,2,6)],rate.cat=2,node.states="marginal")
pp.polymorphic13d
pp.polymorphic13d.1<-corHMM(mytree,trait13[,c(1,2,6)],rate.cat=1,node.states="marginal")
pp.polymorphic13d.1
pp.polymorphic13d.2<-corHMM(mytree,trait13[,c(1,2,6)],rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic13d.2
pp.polymorphic13d.3<-corHMM(mytree,trait13[,c(1,2,6)],rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic13d.3




#open_close_wind_animal
pdffn = paste0("corHMMmodel_open_close_wind_animal.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic13a, rate.cat = 2, color = "col.blind" )
dev.off()

#"0_0" "0_1" "1_0" "1_1" 
cols <- c("white", "black", "blue", "purple", "red", "yellow", "orange", "green")
pdffn = paste0("polymorphicARDandR1R2rates_open_close_wind_animal.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic13a$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Open Close Wind Animal ARD and R1/R2 rates")
dev.off()

trait <- paste(trait13[,2],trait13[,3], sep = "_") 
names(trait) <- trait13[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_open_close_wind_animal.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "blue", "purple", "red", "yellow", "orange", "green")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animal.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animal.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
dev.off()

#1     2     3     4 
#"0_0" "0_1" "1_0" "1_1" 
#(1,R1)      (2,R1)      (3,R1)       (4,R1)      (1,R2)      (2,R2)      (3,R2)  (4,R2)

cols <- c("orange", "orange", "orange", "orange", "grey", "grey", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animalrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animalrates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("pink", "pink", "brown", "brown", "pink", "pink", "brown", "brown")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animalhabitat.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animalhabitat.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
dev.off()


cols <- c("green", "blue", "green", "blue", "green", "blue","green", "blue")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animalpollination.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_close_wind_animalpollination.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13a$states,piecol=cols,cex=0.1)
dev.off()

#open_close_wet_dry
pdffn = paste0("corHMMmodel_open_close_wet_dry.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic13b.2, rate.cat = 2, color = "col.blind" )
dev.off()

#"0_0" "0_1" "1_0" "1_1" 
cols <- c("white", "black", "blue", "purple", "red", "yellow", "orange", "green")
pdffn = paste0("polymorphicSYMandR1R2rates_open_close_wet_dry.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic13b.2$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Open Close Wet Dry SYM and R1/R2 rates")
dev.off()

trait <- paste(trait13[,2],trait13[,4], sep = "_") 
names(trait) <- trait13[,1]
pdffn = paste0("polymorphicSYMandR1R2ratesv2_open_close_wet_dry.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "blue", "purple", "red", "yellow", "orange", "green")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_dry.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_dry.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
dev.off()

#1     2     3     4 
#"0_0" "0_1" "1_0" "1_1" 
#(1,R1)      (2,R1)      (3,R1)       (4,R1)      (1,R2)      (2,R2)      (3,R2)  (4,R2)

cols <- c("orange", "orange", "orange", "orange", "grey", "grey", "grey", "grey")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_dryrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_dryrates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("pink", "pink", "brown", "brown", "pink", "pink", "brown", "brown")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_dryhabitat.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_dryhabitat.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
dev.off()


cols <- c("green", "blue", "green", "blue", "green", "blue","green", "blue")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_drywetness.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicSYMandR1R2ratesfan_open_close_wet_drywetness.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic13b.2$states,piecol=cols,cex=0.1)
dev.off()

#open_close

pdffn = paste0("corHMMmodel_open_closed.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12c, rate.cat = 2, color = "col.blind")
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2rates_open_closed.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12c$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Open Close ARD and R1/R2 rates")
dev.off()

trait <- trait12[,2]
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_open_closed.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closed.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closed.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
dev.off()


# 1   2 
#"0" "1" 
# (1,R1)      (2,R1)     (1,R2)      (2,R2)
cols <- c("orange", "orange", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closerates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closerates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("pink", "brown", "pink", "brown")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closehabitat.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closehabitat.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12c$states,piecol=cols,cex=0.1)
dev.off()

#annual_perennial
pdffn = paste0("corHMMmodel_annual_perennial.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12d, rate.cat = 2, color = "col.blind")
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2rates_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12d$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Annual Perennial ARD and R1/R2 rates")
dev.off()

trait <- trait12[,3]
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("red", "yellow","white", "black")
pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennial.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennial.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
dev.off()


cols <- c("orange", "orange", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialrates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("green", "blue", "green", "blue")
pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialhabit.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennialhabit.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12d$states,piecol=cols,cex=0.1)
dev.off()

#photosynthesis

pdffn = paste0("corHMMmodel_C3C4CAM.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic12e, rate.cat = 2, color = "col.blind" )
dev.off()

cols <- c("white", "black", "blue", "red", "yellow", "orange")
pdffn = paste0("polymorphicARDandR1R2rates_C3C4CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic12e$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="C3C4CAM ARD and R1/R2 rates")
dev.off()

trait <- trait12[,4]
names(trait) <- trait12[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_C3C4CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "blue", "red", "yellow", "orange")
pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAM.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAM.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
dev.off()

# 1   2   3 
#"0" "1" "2" 
# (1,R1)      (2,R1)       (3,R1)      (1,R2)      (2,R2)      (3,R2)

cols <- c("orange", "orange", "orange", "grey", "grey", "grey")
pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMrates.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMrates.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
dev.off()

cols <- c("green", "blue", "red", "green", "blue", "red")
pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMphoto.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_C3C4CAMphoto.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic12e$states,piecol=cols,cex=0.1)
dev.off()
```





Old analyses



```{r}

#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree <- read.tree(file="Poales_supertree_calibrated.nwk")
tree


trait1 <- cbind(traits$WCVP_name, traits$open_closed)
#open_closed
trait1
trait1[,2][trait1[,2] == ""] <- NA
trait1[,2][trait1[,2] == "1"] <- 1
trait1[,2][trait1[,2] == "0"] <- 0
trait1[,2][trait1[,2] == "01"] <- 1
trait1<-trait1[!is.na(trait1[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait1[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic<-corHMM(mytree,trait1,rate.cat=2,node.states="marginal")
pp.polymorphic
pp.polymorphic.1<-corHMM(mytree,trait1,rate.cat=1,node.states="marginal")
pp.polymorphic.1
pp.polymorphic.2<-corHMM(mytree,trait1,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic.2
pp.polymorphic.3<-corHMM(mytree,trait1,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic.3


pdffn = paste0("corHMMmodel_open_closed.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2rates_open_closed.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic ARD and R1/R2 rates")
dev.off()

trait <- trait1[,2]
names(trait) <- trait1[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_open_closed.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closed.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicARDandR1R2ratesfan_open_closed.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic$states,piecol=cols,cex=0.1)
dev.off()


```


```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree <- read.tree(file="Poales_supertree_calibrated.nwk")
tree

trait4 <- cbind(traits$WCVP_name, traits$annual_perennial)
#annual_perennial
trait4
trait4[,2][trait4[,2] == ""] <- NA
trait4[,2][trait4[,2] == "1"] <- 1
trait4[,2][trait4[,2] == "0"] <- 0
trait4[,2][trait4[,2] == "01"] <- 1
trait4<-trait4[!is.na(trait4[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait4[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic4<-corHMM(mytree,trait4,rate.cat=2,node.states="marginal")
pp.polymorphic4
pp.polymorphic4.1<-corHMM(mytree,trait4,rate.cat=1,node.states="marginal")
pp.polymorphic4.1
pp.polymorphic4.2<-corHMM(mytree,trait4,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic4.2
pp.polymorphic4.3<-corHMM(mytree,trait4,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic4.3


pdffn = paste0("corHMMmodel_annual_perennial.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic4, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2rates_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic4$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic ARD and R1/R2 rates")
dev.off()

trait <- trait4[,2]
names(trait) <- trait4[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_annual_perennial.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic4$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennial.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic4$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicARDandR1R2ratesfan_annual_perennial.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic4$states,piecol=cols,cex=0.1)
dev.off()

```




```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree

trait2 <- cbind(traits$WCVP_name, traits$C4)
#C4
trait2
trait2[,2][trait2[,2] == ""] <- NA
trait2[,2][trait2[,2] == "1"] <- 1
trait2[,2][trait2[,2] == "0"] <- 0
trait2[,2][trait2[,2] == "01"] <- 1
trait2<-trait2[!is.na(trait2[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait2[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic2<-corHMM(mytree,trait2,rate.cat=2,node.states="marginal")
pp.polymorphic2
pp.polymorphic2.1<-corHMM(mytree,trait2,rate.cat=1,node.states="marginal")
pp.polymorphic2.1
pp.polymorphic2.2<-corHMM(mytree,trait2,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic2.2
pp.polymorphic2.3<-corHMM(mytree,trait2,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic2.3


pdffn = paste0("corHMMmodel_c4.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic2, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2rates_c4.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic2$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic ARD and R1/R2 rates")
dev.off()

trait <- trait2[,2]
names(trait) <- trait2[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_c4.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic2$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2ratesfan_c4.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

```


```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree

trait3 <- cbind(traits$WCVP_name, traits$wind_animal)
#wind_animal
trait3
trait3[,2][trait3[,2] == ""] <- NA
trait3[,2][trait3[,2] == "1"] <- 1
trait3[,2][trait3[,2] == "0"] <- 0
trait3[,2][trait3[,2] == "01"] <- 1
trait3<-trait3[!is.na(trait3[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait3[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic3<-corHMM(mytree,trait3,rate.cat=2,node.states="marginal")
pp.polymorphic3
pp.polymorphic3.1<-corHMM(mytree,trait3,rate.cat=1,node.states="marginal")
pp.polymorphic3.1
pp.polymorphic3.2<-corHMM(mytree,trait3,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic3.2
pp.polymorphic3.3<-corHMM(mytree,trait3,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic3.3


pdffn = paste0("corHMMmodel_wind_animal.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic3.2, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2rates_wind_animal.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic3.2$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic SYM and R1/R2 rates")
dev.off()

trait <- trait3[,2]
names(trait) <- trait3[,1]
pdffn = paste0("polymorphicSYMandR1R2ratesv2_wind_animal.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic3.2$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_wind_animal.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic3.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicSYMandR1R2ratesfan_wind_animal.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic3.2$states,piecol=cols,cex=0.1)
dev.off()

```





```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree

trait5 <- cbind(traits$WCVP_name, traits$CAM)
#CAM
trait5
trait5[,2][trait5[,2] == ""] <- NA
trait5[,2][trait5[,2] == "1"] <- 1
trait5[,2][trait5[,2] == "0"] <- 0
trait5[,2][trait5[,2] == "01"] <- 1
trait5<-trait5[!is.na(trait5[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait5[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic5<-corHMM(mytree,trait5,rate.cat=2,node.states="marginal")
pp.polymorphic5
pp.polymorphic5.1<-corHMM(mytree,trait5,rate.cat=1,node.states="marginal")
pp.polymorphic5.1
pp.polymorphic5.2<-corHMM(mytree,trait5,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic5.2
pp.polymorphic5.3<-corHMM(mytree,trait5,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic5.3


pdffn = paste0("corHMMmodel_CAM.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic5, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2rates_CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic5$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic ARD and R1/R2 rates")
dev.off()

trait <- trait5[,2]
names(trait) <- trait5[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_CAM.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic5$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2ratesfan_CAM.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F, cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic5$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

```



```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree

trait6 <- cbind(traits$WCVP_name, traits$silica)
#silica
trait6
trait6[,2][trait6[,2] == ""] <- NA
trait6[,2][trait6[,2] == "1"] <- 1
trait6[,2][trait6[,2] == "0"] <- 0
trait6[,2][trait6[,2] == "01"] <- 1
trait6<-trait6[!is.na(trait6[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait6[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic6<-corHMM(mytree,trait6,rate.cat=2,node.states="marginal")
pp.polymorphic6
pp.polymorphic6.1<-corHMM(mytree,trait6,rate.cat=1,node.states="marginal")
pp.polymorphic6.1
pp.polymorphic6.2<-corHMM(mytree,trait6,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic6.2
pp.polymorphic6.3<-corHMM(mytree,trait6,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic6.3

pdffn = paste0("corHMMmodel_sillica.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic6.2, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2rates_silica.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic6.2$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic SYM and R1/R2 rates")
dev.off()

trait <- trait6[,2]
names(trait) <- trait6[,1]
pdffn = paste0("polymorphicSYMandR1R2ratesv2_silica.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic6.2$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_silica.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic6.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

```


```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree

trait7 <- cbind(traits$WCVP_name, traits$wet)
#wet
trait7
trait7[,2][trait7[,2] == ""] <- NA
trait7[,2][trait7[,2] == "1"] <- 1
trait7[,2][trait7[,2] == "0"] <- 0
trait7[,2][trait7[,2] == "01"] <- 1
trait7<-trait7[!is.na(trait7[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait7[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic7<-corHMM(mytree,trait7,rate.cat=2,node.states="marginal")
pp.polymorphic7
pp.polymorphic7.1<-corHMM(mytree,trait7,rate.cat=1,node.states="marginal")
pp.polymorphic7.1
pp.polymorphic7.2<-corHMM(mytree,trait7,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic7.2
pp.polymorphic7.3<-corHMM(mytree,trait7,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic7.3

pdffn = paste0("corHMMmodel_wet.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic7.2, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2rates_wet.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic7.2$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic SYM and R1/R2 rates")
dev.off()

trait <- trait7[,2]
names(trait) <- trait7[,1]
pdffn = paste0("polymorphicSYMandR1R2ratesv2_wet.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic7.2$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_wet.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic7.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicSYMandR1R2ratesfan_wet.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic7.2$states,piecol=cols,cex=0.1)
dev.off()

```



```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree

trait8 <- cbind(traits$WCVP_name, traits$open_wet)
#open_wet
trait8
trait8[,2][trait8[,2] == ""] <- NA
trait8[,2][trait8[,2] == "1"] <- 1
trait8[,2][trait8[,2] == "0"] <- 0
trait8[,2][trait8[,2] == "01"] <- 1
trait8<-trait8[!is.na(trait8[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait8[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic8<-corHMM(mytree,trait8,rate.cat=2,node.states="marginal")
pp.polymorphic8
pp.polymorphic8.1<-corHMM(mytree,trait8,rate.cat=1,node.states="marginal")
pp.polymorphic8.1
pp.polymorphic8.2<-corHMM(mytree,trait8,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic8.2
pp.polymorphic8.3<-corHMM(mytree,trait8,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic8.3

pdffn = paste0("corHMMmodel_wet_open.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic8, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2rates_wet_open.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic8$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic ARD and R1/R2 rates")
dev.off()

trait <- trait8[,2]
names(trait) <- trait8[,1]
pdffn = paste0("polymorphicARDandR1R2ratesv2_wet_open.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic8$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicARDandR1R2ratesfan_wet_open.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic8$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

```



```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree

trait9 <- cbind(traits$WCVP_name, traits$epiphyte)
#epiphyte
trait9
trait9[,2][trait9[,2] == ""] <- NA
trait9[,2][trait9[,2] == "1"] <- 1
trait9[,2][trait9[,2] == "0"] <- 0
trait9[,2][trait9[,2] == "01"] <- 1
trait9<-trait9[!is.na(trait9[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait9[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic9<-corHMM(mytree,trait9,rate.cat=2,node.states="marginal")
pp.polymorphic9
pp.polymorphic9.1<-corHMM(mytree,trait9,rate.cat=1,node.states="marginal")
pp.polymorphic9.1
pp.polymorphic9.2<-corHMM(mytree,trait9,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic9.2
pp.polymorphic9.3<-corHMM(mytree,trait9,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic9.3

pdffn = paste0("corHMMmodel_epiphyte.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic9.2, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2rates_epiphyte.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic9.2$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic SYM and R1/R2 rates")
dev.off()

trait <- trait9[,2]
names(trait) <- trait9[,1]
pdffn = paste0("polymorphicSYMandR1R2ratesv2_epiphyte.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic9.2$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_epiphyte.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan",cex=1, show.tip.label = F,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic9.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()


pdffn = paste0("polymorphicSYMandR1R2ratesfan_epiphyte.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan",cex=1, show.tip.label = F,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic9.2$states,piecol=cols,cex=0.1)
dev.off()

```





```{r}
#install.packages("corHMM")
library(corHMM)
library(phytools)

load("hisse.RData")
ls()
traits
tree <- read.tree(file="Poales_supertree_calibrated.nwk")
tree

trait10 <- cbind(traits$WCVP_name, traits$C4)
#nonC3

trait
trait10[,2][trait10[,2] == ""] <- NA
trait10[,2][trait5[,2] == 1] <- 1
trait10[,2][trait10[,2] == "1"] <- 1
trait10[,2][trait10[,2] == "0"] <- 0
trait10[,2][trait10[,2] == "01"] <- 1
trait10<-trait10[!is.na(trait10[,2]),]
tipstoremove <- setdiff(tree$tip.label,trait10[,1])
mytree <- drop.tip(tree, tipstoremove)

pp.polymorphic10<-corHMM(mytree,trait10,rate.cat=2,node.states="marginal")
pp.polymorphic10
pp.polymorphic10.1<-corHMM(mytree,trait10,rate.cat=1,node.states="marginal")
pp.polymorphic10.1
pp.polymorphic10.2<-corHMM(mytree,trait10,rate.cat=2, model = "SYM", node.states="marginal")
pp.polymorphic10.2
pp.polymorphic10.3<-corHMM(mytree,trait10,rate.cat=1,model = "SYM", node.states="marginal")
pp.polymorphic10.3

pdffn = paste0("corHMMmodel_nonC3.pdf")
pdf(file=pdffn, width=8, height=8)
plotMKmodel(pp.polymorphic10.2, rate.cat = 2, color = c("orange", "blue"))
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2rates_nonC3.pdf")
pdf(file=pdffn, width=6, height=200)
plotRECON(mytree,pp.polymorphic10.2$states,piecolors=cols, cex=0.2, pie.cex=0.3, show.tip.label=TRUE, title="Polymorphic SYM and R1/R2 rates")
dev.off()

trait <- trait10[,2]
names(trait) <- trait10[,1]
pdffn = paste0("polymorphicSYMandR1R2ratesv2_nonC3.pdf")
pdf(file=pdffn, width=6, height=200)
plot(mytree,type="phylogram",cex=0.2,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic10.2$states,piecol=cols,cex=0.3)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

cols <- c("white", "black", "red", "yellow")
pdffn = paste0("polymorphicSYMandR1R2ratesfan_nonC3.pdf")
pdf(file=pdffn, width=100, height=100)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic10.2$states,piecol=cols,cex=0.1)
add.simmap.legend(colors=cols,prompt=FALSE,x=0.9*par()$usr[1],
    y=0.8*par()$usr[3],fsize=2)
dev.off()

pdffn = paste0("polymorphicSYMandR1R2ratesfan_nonC3.jpg")
jpeg(file=pdffn, width=3500, height=3500)
plot(mytree,type="fan", show.tip.label = F,cex=1,font=3,lwd=0.5,label.offset = 1)
tiplabels(pie=to.matrix(trait[mytree$tip.label],
    levels(as.factor(trait))),piecol=cols,cex=0.1)
nodelabels(node=1:mytree$Nnode+Ntip(mytree),
    pie=pp.polymorphic10.2$states,piecol=cols,cex=0.1)
dev.off()

```

